StoreVirtual/Areas/Funcionario/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StoreVirtual.Models;
using StoreVirtual.Repositories.Interfaces;
using StoreVirtual.Service.Filter;
using StoreVirtual.Service.Lang;
using System.Collections.Generic;
using System.Linq;
using X.PagedList;

namespace StoreVirtual.Areas.Funcionario.Controllers
{
    [Area("Funcionario")]
    [FuncionarioAuthorization]
    public class CategoriaController : Controller
    {
        private readonly ICategoriaRepository _categoriaRepository;

        public CategoriaController(ICategoriaRepository categoriaRepository)
        {
            _categoriaRepository = categoriaRepository;
        }

        public IActionResult Index(int? page)
        {
            IPagedList<Categoria> list = _categoriaRepository.FindAlls(page);           
            
            return View(list);
        }
        [HttpGet]
        public IActionResult Insert()
        {
            ViewBag.Categoria = _categoriaRepository.FindAlls().Select(x => new SelectListItem(x.Nome, x.Id.ToString()));
            return View();
        }

        [HttpPost]
        public IActionResult Insert(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _categoriaRepository.Insert(categoria);
                TempData["MSG_S"] = Message.MSG_S006;
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categoria = _categoriaRepository.FindAlls().Select(x=> new SelectListItem(x.Nome,x.Id.ToString()));
            return View();
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            Categoria cat = _categoriaRepository.FindById(id);
            ViewBag.Categoria = _categoriaRepository.FindAlls().Where(x=>x.Id != id).Select(x => new SelectListItem(x.Nome, x.Id.ToString()));
            return View(cat);
        }
        [HttpPost]
        public IActionResult Update(Categoria categoria, int id)
        {
            if (ModelState.IsValid)
            {
                _categoriaRepository.Update(categoria);
                TempData["MSG_S"] = Message.MSG_S007;
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categoria = _categoriaRepository.FindAlls().Where(x => x.Id != id).Select(x => new SelectListItem(x.Nome, x.Id.ToString()));
            return View();
        }

        [HttpGet]
        [ValidationHttpReferer]

        public IActionResult Remove(int id)
        {
            _categoriaRepository.Delete(id);
            TempData["MSG_S"] = Message.MSG_S008;
            return RedirectToAction(nameof(Index));
        }
    }
}

StoreVirtual/Areas/Funcionario/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using StoreVirtual.Models;
using StoreVirtual.Models.Constants;
using StoreVirtual.Repositories.Interfaces;
using StoreVirtual.Service.Filter;
using StoreVirtual.Service.Lang;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace StoreVirtual.Areas.Funcionario.Controllers
{
    [Area("Funcionario")]
    [FuncionarioAuthorization]
    public class ClienteController : Controller
    {
        private readonly IClienteRepository _clienteRepository;

        public ClienteController(IClienteRepository clienteRepository)
        {
            _clienteRepository = clienteRepository;
        }

        public IActionResult Index(int? page, string search)
        {
            IPagedList<Cliente> clientes = _clienteRepository.FindAll(page, search);
            return View(clientes);
        }
        [ValidationHttpReferer]
        public IActionResult AtivarDesativar(int id)
        {
            Cliente cliente = _clienteRepository.FindById(id);
            cliente.Situacao = (cliente.Situacao == ClienteTypeConstant.Ativo) ? ClienteTypeConstant.Desativado : ClienteTypeConstant.Ativo;
            _clienteRepository.Update(cliente);

            TempData["MSG_S"] = Message.MSG_S007;

            return RedirectToAction(nameof(Index));
        }
    }
}

StoreVirtual/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using StoreVirtual.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreVirtual.Controllers
{
    public class ProdutoController : Controller
    {
        public ActionResult Visualizar()
        {
            Produto view = GetProduto();
            return View(view);
        }

        private Produto GetProduto()
        {
            return new Produto
            {
                Id = 1,
                Descricao = "Descricao",
                Nome = "Nome",
                Valor = 25.50M
            };
        }
    }
}

StoreVirtual/Areas/Funcionario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>@ViewBag.Title</title>

    <!-- Bootstrap core CSS -->
    <link href="~/resources/lib/bootstrap-4.2.1-dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/resources/lib/pagedList/pagedList.css" rel="stylesheet" type="text/css" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" type="text/css" />

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @@media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="~/resources/lib/dashboard/dashboard.css" rel="stylesheet">
</head>
<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Store Virtual</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" asp-action="Forgot" asp-area="Funcionario" asp-controller="Home">Sair</a>
            </li>
        </ul>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-action="Painel">
                                <span data-feather="home"></span>
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file"></span>
                                Pedidos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Categoria">
                                <span data-feather="shopping-cart"></span>
                                Categorias
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Produto">
                                <span data-feather="shopping-cart"></span>
                                Produtos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Funcionario">
                                <span data-feather="users"></span>
                                Funcionarios
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Cliente">
                                <span data-feather="users"></span>
                                Clientes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bar-chart-2"></span>
                                Relatórios
                            </a>
                        </li>
                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Saved reports</span>
                        <a class="link-secondary" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Current month
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Last quarter
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Social engagement
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Year-end sale
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <main class="offset-2 col-lg-10">
                @RenderBody()
            </main>

        </div>
    </div>


    <script src="~/resources/lib/bootstrap-4.2.1-dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/resources/lib/jquery3.3.1/jquery-3.3.1.min.js"></script>
    <script src="~/resources/lib/feather/feather.js"></script>
    <script src="~/resources/lib/charts/charts.js"></script>
    <script src="~/resources/lib/dashboard/dashboard.js"></script>
    <script src="~/resources/lib/js/actions.js"></script>
    <script src="~/resources/lib/dist/jquery.mask.js"></script>


</body>
</html>